apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment
  namespace: tpjad-hw1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfly
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
        - name: wildfly
          image: wildfly-custom:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wildfly-service
  namespace: tpjad-hw1
spec:
  selector:
    app: wildfly
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP